### ISSUE TITLE
Can't fork with latest pip version

### ISSUE THREAD

**Issue by mjlabe** [LabD/django-oscar-wagtail#11]
django-oscar==1.6.6
django-oscar-wagtail==0.2.0
wagtail==2.3

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/my/project/directory/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/my/project/directory/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/my/project/directory/venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/my/project/directory/venv/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/my/project/directory/venv/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/my/project/directory/venv/lib/python3.6/site-packages/oscar_wagtail/models.py", line 5, in <module>
    from wagtail.wagtailadmin.edit_handlers import (FieldPanel, InlinePanel,)
ModuleNotFoundError: No module named 'wagtail.wagtailadmin'
```

**Comment by mjlabe** [comment]
If I start with Django and oscar and add wagtail as an app I can get it to install (and fork).

**Comment by soypunk** [comment]
@mjlabe would you mind explaining how you get things up and running? I'm hitting this same error and I'm fairly sure I built up my Django stack the same way you did.

**Comment by Mrangulo-Ke** [comment]
I hit the same error

**Comment by mjlabe** [comment]
> @mjlabe would you mind explaining how you get things up and running? I'm hitting this same error and I'm fairly sure I built up my Django stack the same way you did.

I was trying to add Oscar to wagtail, but I had to start with Oscar by following the instructions and add wagtail after. I quickly gave up though because it's not very customizable, doesn't seem active, and was not pleasant to work with.

**Comment by jeffykle** [comment]
@mjlabe have you found anything suitable? I like wagtail and want to add some e-commerce functionality without getting into anything too complex. I was also looking at [Satchless](https://github.com/mirumee/satchless/blob/master/doc/index.rst) but it seems lacking in documentation and generally fallen to the wayside.

**Comment by mjlabe** [comment]
No, I've actually stopped using both. I've found writing my own to be faster than trying to pigeon hole the projects.

**Comment by herbkora** [comment]
From wagtail 2.0 many of the modules were renamed e.g **wagtail.wagtailadmin** is now **wagtail.admin**, your will have to fork django-oscar-wagtail and rename the modules to have it up and running. [Documentation](https://docs.wagtail.io/en/v2.1.1/releases/2.0.html)
